name: .NET 4.6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5      
      
    - name: Restore NuGet packages
      run: nuget restore LuaSettings.sln
      
    - name: Build
      run: msbuild LuaSettings.sln /p:Configuration=Release
      
    - name: Auto Release  
      uses: CupOfTea696/gh-action-auto-release@v1.0.2
      with:
        # Title for the release
        #title: # optional, default is Version $semver
        # Name for the git tag
        #tag: # optional, default is $version
        # Whether or not this release should be published as a draft
        draft: true # optional, default is false
        # The path to the CHANGELOG
        #changelog: # optional, default is CHANGELOG.md
        # String a CHANGELOG entry must contain to be used as the entry for this release
        #changelog-entry: # optional, default is $version
        # Pattern the commit message must match to create a release
        #regex: # optional
        # Pattern the commit message must match to mark the release as a prerelease
        #prerelease-regex: # optional
      
