name: .NET 4.6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5      
      
    - name: Restore NuGet packages
      run: nuget restore LuaSettings.sln
      
    - name: Build
      run: msbuild LuaSettings.sln /p:Configuration=Release
      
    - name: generate-changelog-action
      uses: ScottBrenner/generate-changelog-action@1.0.0
      id: Changelog
      env:
        REPO: ${{ github.repository }}
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: bin/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
